src/objects/Designation__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Germany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Designation__c</fullName>
        <label>Designation</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>OpportunityM_D__c</fullName>
        <label>OpportunityM_D</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Designations</relationshipLabel>
        <relationshipName>Designations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Test_Salesforce__c</fullName>
        <label>Test Salesforce</label>
        <referenceTo>New_Salesforce__c</referenceTo>
        <relationshipLabel>Designations</relationshipLabel>
        <relationshipName>Designations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Designation</label>
    <nameField>
        <label>Designation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Designations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/New_Salesforce__c.object
<CustomObject>
    <label>New Salesforce</label>
    <nameField>
        <label>New Salesforce Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>New Salesforce</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDesignationController.cls
@isTest
public class TestDesignationController{


@TestSetup
public static void genericMethod(){

List<Designation__c> designation = new List<Designation__c>();
List<Opportunity> opportunity = new List<Opportunity>();
List<New_Salesforce__c> newSFDC = new List<New_Salesforce__c>();


for(Integer a=0;a<=150;a++){
New_Salesforce__c newSFDC1 = new New_Salesforce__c();

newSFDC1.Name = 'New Test'+a;
System.debug(' new sfdc  ---  '+a);
newSFDC.add(newSFDC1);

}

insert newSFDC;


for(Integer b=0;b<=150;b++){

Opportunity newOppty = new Opportunity();

newOppty.CloseDate= System.Today()+10;
newOppty.Name= 'New Oppty'+b;
newOppty.StageName= 'Prospecting';
System.debug('Opportunity   ---  '+b);
opportunity.add(newOppty);
}
insert opportunity;


for(Integer c=0;c<=150;c++){

Designation__c desig = new Designation__c();
desig.DOB__c = System.Today();
desig.OpportunityM_D__c = opportunity[0].Id;
desig.Test_Salesforce__c = newSFDC[0].Id;
desig.Name = 'I love my India'+c;
desig.Email__c ='abc@abc.com';
desig.Mobile__c = '8106269898';
desig.Country__c= 'India';
System.debug('desig   ---  '+c);

designation.add(desig);
}
insert designation;

//create one user record one user profile

}


//first method
public static testmethod void method1(){

Test.startTest();
List<Designation__c> di = [select Id, Name from Designation__c];

for(Designation__c designat : di){

system.debug('  method 1 values ----   '+designat.Name);


}


Test.stopTest();
}

//second method
public static testmethod void method2(){

Test.startTest();

System.assertEquals(151,[select count() from Opportunity]);
System.assertEquals(151,[select count() from New_salesforce__c]);
 
//get the user record from user object 
List<Designation__c> di = [select Id, Name from Designation__c];
DesignationController con = new DesignationController();
con.designationUpdate(di);
Test.stopTest();
}


}