src/objects/Evening_Object__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Evening Objects</relationshipLabel>
        <relationshipName>Evening_Objects</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Evening Objects</relationshipLabel>
        <relationshipName>Evening_Objects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Evening Objects</relationshipLabel>
        <relationshipName>Evening_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>testing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>testing</label>
        <referenceTo>testing__c</referenceTo>
        <relationshipLabel>Evening Objects</relationshipLabel>
        <relationshipName>Evening_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Evening Object</label>
    <nameField>
        <label>Evening Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evening Objects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/testing__c.object
<CustomObject>
    <label>testing</label>
    <nameField>
        <label>testing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>testings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestingController.cls
Public class TestingController{


public TestingController(){

}

public static void beforeInsertRecord(List<testing__c> testNew){

System.debug('  -First method--   ');

for(testing__c listnew :testNew){

if(listnew.Name!=null){
listnew.Name = 'before insert current record';
}


}


}
public static void beforeUpdateRecord(List<testing__c> testNew){

System.debug('  -First update method--   ');

for(testing__c listnew :testNew){

if(listnew.Name!=null){
listnew.Name = 'before update current record';
}


}

}

public static void afterInsertRecord(List<testing__c> testNew){

System.debug('  -First update method--   ');

List<Opportunity> opp = [Select Id from Opportunity limit 1];
List<Account> acc = [Select Id from Account limit 1];
List<Case> cas = [Select Id from Case limit 1];

Evening_Object__c evObject = new Evening_Object__c();
for(testing__c listnew :testNew){
evObject.testing__c = listnew.Id;
evObject.Name = 'afterInsertRecord Creation';            
evObject.Account_Name__c = acc[0].Id;
evObject.Case__c = cas[0].Id;
evObject.Opportunity__c = opp[0].Id;
evObject.Phone__c ='8106269898';

}
insert evObject;

}


public static void afterUpdateRecord(List<testing__c> testNew){

List<Evening_Object__c>  listEve = new List<Evening_Object__c>();
List<Evening_Object__c> listRe = [Select Id, Name from Evening_Object__c where testing__c=: testNew[0].Id];
for(Evening_Object__c listnew : listRe){
listnew.Name = 'afterUpdateRecord Creation12345';

listEve.add(listnew);
}
update listEve;


}

}